### ISSUE TITLE
1.2.13 not working in netcoreapp3.1

### ISSUE THREAD

**Issue by stonesvillage** [serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative#21] opened 2022-02-25 09:47 UTC
Updated from v1.2.11 to v1.2.13.
Fails in Main when creating Logger:
`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'`

Downgrading to v1.2.12 works but v1.2.13 seems to be broken for netcoreapp3.1.

**Comment by seyes84** [comment] 2022-03-01 17:26
Yes, same for me. 
.NET 5, got same error.

**Comment by SeppPenner** [comment] 2022-03-02 07:36
1.2.12 should be the latest version... Maybe, I accidently added 1.2.13 to NuGet while playing around with the build script. It was not intended to be published... I will provide an updated version soon, for now please stay with 1.2.12 or lower.

**Comment by SeppPenner** [comment] 2022-03-02 18:21
Version 1.2.14 should be there soon and fixed. I have updated the changelog with information to not use 1.2.13 as its a broken build.

**Comment by radxhunter** [comment] 2022-03-31 08:34
Installed v1.2.14.
Fails when building the multi target app for .net5 and netcoreapp3.1
  <TargetFrameworks>netcoreapp3.1;net5.0;net6.0</TargetFrameworks>

`Assembly 'Serilog.Sinks.MicrosoftTeams.Alternative' with identity 'Serilog.Sinks.MicrosoftTeams.Alternative, Version=1.2.14.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Some.Business.App(netcoreapp3.1)`

Downgrading to v1.2.12 works for every version, is something wrong with v1.2.14 too?

**Comment by SeppPenner** [comment] 2022-04-03 13:42
> Installed v1.2.14. Fails when building the multi target app for .net5 and netcoreapp3.1 netcoreapp3.1;net5.0;net6.0
> 
> `Assembly 'Serilog.Sinks.MicrosoftTeams.Alternative' with identity 'Serilog.Sinks.MicrosoftTeams.Alternative, Version=1.2.14.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Some.Business.App(netcoreapp3.1)`
> 
> Downgrading to v1.2.12 works for every version, is something wrong with v1.2.14 too?

Version 1.2.14 should be alright. I need to investigate further.

**Comment by SeppPenner** [comment] 2022-04-03 19:08
I have no idea yet, what's wrong there... I have updated the NuGet packages once again and made 1.2.15. Hopefully, this fixes the issue. I don't see build errors (I run the build for NetStandard2.0, NetStandard2.1, NetCore3.1, Net5.0 and Net6.0 in parallel with no issues).

Please let me know if the new version works. If not, I need to investigate with an example NetCore3.1 project, I guess :D

**Comment by SeppPenner** [comment] 2022-04-10 17:22
I assume that this is now fixed. If not, I will check it again. Please let me know if there are any problems.

**Comment by radxhunter** [comment] 2022-04-20 06:44
Hi, still have got the same issue :(
![image](https://user-images.githubusercontent.com/61984102/164166874-3e68f9d9-d872-442a-a95b-2b655bd31af4.png)

**Comment by SeppPenner** [comment] 2022-04-21 13:20
Ok, I will have to check it again. This seems to be related to https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative/issues/49 although the projects are different ones...

**Comment by SeppPenner** [comment] 2022-05-22 18:42
>CSC : error CS1705: Assembly "Serilog.Sinks.MicrosoftTeams.Alternative" mit Identität "Serilog.Sinks.MicrosoftTeams.Alternative, Version=1.2.15.0, Culture=neutral, PublicKeyToken=null" verwendet "System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" mit einer höheren Version als die referenzierte Assembly "System.Runtime" mit Identität "System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

The question is why? There is no `System.Runtime, Version=4.2.2.0` in the deps.json file for NetCore3.1. The only referenced version is "System.Runtime": "4.3.0"...

**Comment by adte** [comment] 2022-11-08 09:50
I also get the same error on version 1.2.20.0
In my opinion, the problem is building libraries for nuget because when I downloaded and decompiled all libraries were prepared for .netCore6, no matter if it was .net standard or .net6
![image](https://user-images.githubusercontent.com/2039653/200532177-ffd7cd66-2ccb-415b-a314-c5b8ca5be555.png)

**Comment by SeppPenner** [comment] 2022-11-08 10:22
Strange... I do nothing special when building the NuGet package in comparison to the others (E.g. Serilog.Sinks.AmazonS3)... If anyone has an idea, please contact me. I have already searched several times, but found no useful hints yet...

**Comment by SeppPenner** [comment] 2022-11-08 10:24
@augustoproiete Did you maybe see some problem like this somewhere else before?

**Comment by SeppPenner** [comment] 2023-04-07 14:55
I will close this issue now. The main reason is that I have absolutely no idea why this happens...

**Closed as completed by SeppPenner** 2023-04-07 14:55 UTC
Labels: bug
